# Generated by Django 5.2.8 on 2025-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', max_length=20),
        ),
    ]
