# Generated by Django 5.2.8 on 2025-12-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.JSONField(default=dict)),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
        ),
    ]
