# Generated by Django 6.0 on 2025-12-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gradehorario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
