# Generated by Django 5.2.8 on 2025-12-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_superperfil_delete_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperPerfil',
        ),
    ]
