# Generated by Django 5.2.8 on 2025-11-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='cargo',
            field=models.CharField(choices=[('diretor', 'Diretor'), ('vice_diretor', 'Vice-Diretor'), ('secretario', 'Secretário'), ('coordenador', 'Coordenador')], max_length=20),
        ),
    ]
